version: 2
jobs:
  checks:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.4
    steps:
      - checkout
      - run:
          name: PHP-Lint
          no_output_timeout: 20m
          command: parallel-lint --exclude vendor /root/project/var/www/
      # - run:
      #     name:            PHP-Code-Fix
      #     no_output_timeout: 20m
      #     command:         phpcbf /root/project/var/www/
      # - run:
      #     name:            PHP-CS
      #     no_output_timeout: 20m
      #     command:         phpcs --extensions=php /root/project/var/www/
      # - run:
      #     name:            Running phpcs
      #     command:         bash ./bin/php_cs.sh
      # - run:               -- Runs out of RAM
      #     name:            PHP-Var-Dump-Check
      #     no_output_timeout: 20m
      #     command:         var-dump-check /root/project/var/www/
      # - run:               -- Runs out of RAM
      #     name:            PHP Copy/Paste Detector
      #     no_output_timeout: 20m
      #     command:         phpcpd /root/project/var/www/
      - run:
          name:            PHPMD
          no_output_timeout: 20m
          command:         phpmd --ignore-violations-on-exit /root/project/var/www/html/ text cleancode, codesize, controversial, design, naming, unusedcode
  publish:
    docker:
      - image: eu.gcr.io/swade1987/kubernetes-toolkit:1.17.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install docker
          command: make install-docker
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: build docker image
          command: make build
      - run:
          name: Trivy scan
          command: make scan
      - run:
          name: Configure Digital Ocean
          command: make install-doctl-linux
      - run:
          name: Push Image to Digital Ocean
          command: make push-to-digitalocean
  scan:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --update alpine-sdk
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl rpm
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            mv trivy /usr/local/bin
      - run:
          name: trivy scan
          command: make scan
workflows:
  version: 2
  flow:
    jobs:
      - checks
      - publish:
          filters:
            branches:
              only:
                - main
          requires:
            - checks
            # - scan